---
title: "R Notebook"
output: html_notebook
---



```{r}
library(tidyverse)
library(ggplot2)
```


```{r}
data(mpg)
mpg
```

```{r}
mpg %>% #pipe operator "luego"
  add_row(manufacturer = "jeep",
          displ        = 2,
          year         = 2008,
          cyl          = 4,
          trans        ="manual(m6)",
          cty          =15,
          hwy          =24,
          fl           ="p",
          class        ="suv"
          )

```
Si queremos cambiar el fabricante a factor y hwy (que está medida en "millas por galón" a "km por litro"), podemos usar mutate():
```{r}
mpg %>%
  mutate(
    cty = cty * 1.609 / 3.785,
    hwy = hwy * 1.609 / 3.785,
    manufacturer = as_factor(manufacturer),
    model = as_factor(model),
  )

```
```{r}
mpg_editada <- mpg %>%
  mutate_if(
    .predicate = is.character,
    .funs      = as_factor
  )
mpg_editada

```
```{r}
mpg_editada2 <- mpg %>%
  mutate_if(
    .predicate = is.character,
    .funs      = as_factor
  ) %>%
  mutate (trans = fct_lump_min(trans, 20,
                               other_level = "Otros"))
mpg_editada2
```
```{r}
plot(cars)
```
```{r}
mpg_editada2 %>%
  ggplot() +
  geom_point(mapping = aes (x = displ, y = hwy))
```
```{r}
mpg_editada2 %>%
ggplot() +
   geom_point(mapping = aes(x = displ,
                            y = hwy,
                            color = class)
              )

```
```{r}
ggplot(data = mpg_editada2) +
  geom_point(mapping = aes(x = displ,
                           y = hwy,
                           color = class,
                           shape = drv,
                           size = cyl),
             alpha = 0.7)
```
```{r}
mpg_editada2 %>%
  ggplot(aes(x = manufacturer, y = displ)) +
  geom_boxplot()
```
Tidyverse
```{r}
library(tsibble)
```

```{r}
data(world_bank_pop, package = "tidyr")
pop <- world_bank_pop
```

```{r}
head(pop)
```

```{r}
pop_tidy <- pop %>% 
  pivot_longer(cols=-c(country,indicator),
               names_to="year",values_to="value") %>% 
  
  pivot_wider(names_from=indicator,
              values_from=value) %>% 
  
  select(country,year,contains("TOTL")) %>% 
  
  rename(urban_pop=SP.URB.TOTL,total_pop=SP.POP.TOTL) %>% 
  
  mutate(rural_pop_pct=(1-urban_pop/total_pop)*100,
         country=as_factor(country),
         year=as.integer(year)
         ) %>% 
  filter(country %in% c("MEX","BRA","ARG")) %>% 
  
  as_tsibble(key=country,index=year)

pop_tidy
```

